#!/usr/bin/env bash

# cuda 9.2
#export PATH="$PATH:/usr/local/cuda-9.2/bin"
# cuda 10.0
#export PATH="$PATH:/usr/local/cuda-10.0/bin"
export PATH=/usr/local/cuda/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}

# ccache paths
export PATH=/usr/local/bin${PATH:+:${PATH}}
export CCACHE_NOHASHDIR=;
#export CCACHE_DIR="~/.ccache";
export CCACHE_COMPILERCHECK="%compiler% --version";
# Set this to debug ccache preprocessor errors and cache misses
# export CCACHE_LOGFILE="~/.ccache/ccache.log"

# system-wide installed
export PATH="$PATH:/usr/local/cuda/bin"
export PATH="$PATH:$HOME/miniconda3/bin"
export PATH="$PATH:$HOME/.local/bin"
export PARALLEL_LEVEL=12

