#!/bin/sh
[[ "${TERM_PROGRAM}" == "vscode" ]] && export CUDF_HOME=`pwd`

CUDF_HOME=${CUDF_HOME:-$HOME/cudf}
echo "CUDF_HOME: $CUDF_HOME"
export CUDF_HOME=$CUDF_HOME
CUDF_CPP_HOME=$CUDF_HOME/cpp/build
CUDF_PYTHON_HOME=$CUDF_HOME/python/cudf
export NVSTRINGS_ROOT=$CUDF_HOME/cpp/build
export OLD_PYTHONPATH=$PYTHONPATH
export OLD_LD_LIBRARY_PATH=$LD_LIBRARY_PATH
export PYTHONPATH=$PYTHONPATH:$CUDF_PYTHON_HOME:$CUDF_CPP_HOME/python
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CUDF_CPP_HOME
